1

diff --git a/ci/jenkins/Jenkinsfile b/ci/jenkins/Jenkinsfile
--- a/ci/jenkins/Jenkinsfile
+++ b/ci/jenkins/Jenkinsfile
@@ -63,18 +63,23 @@ pipeline {
              docker rm -f test-app || true
              docker run -d -p 8081:80 --name test-app app-image
              
+             trap "docker rm -f test-app" EXIT
+             
              echo "waiting for nginx container to load"
-
-             for i in {1..20}; do
-               if curl -f http://localhost:8081; then
+             for i in {1..40}; do
+               if curl -s http://localhost:8081 > /dev/null; then
                  echo "App is ready"
                  break
                fi
                sleep 2
              done
              
-             curl -f http://localhost:8081
-             docker rm -f test-app
+             if ! curl -f http://localhost:8081; then
+               echo "App failed to start"
+               docker logs test-app
+               exit 1
+             fi
+             
              '''   
            
           }
